name: Generate snake animation
#<p align="left"> <img src="https://komarev.com/ghpvc/?username=dhruvak001&label=Profile%20views&color=0e75b6&style=flat" alt="dhruvak001" /> </p>
on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *" # Ensures proper cron syntax (0 at start for the minute)

  workflow_dispatch: # Allows manual triggering of the workflow

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: dhruvak001
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
